### ISSUE TITLE
ARI project is not resulting into FQCN update when tasks are wrapped under block and when Ansible statements

### ISSUE THREAD

**Issue by justjais** [ansible/ansible-risk-insight#229] opened 2024-05-02 09:21 UTC
ARI project is not resulting into FQCN update when tasks are wrapped under block and when Ansible statements.

Steps to reproduce:
The actual playbook is roles/playbooks/User/check_user_privileges.yml [here](https://github.com/justjais/LoadBotTesting-2/blob/main/roles/playbooks/User/check_user_privileges.yml), and the project ARI scan is run over [LoadBotTesting-2](https://github.com/justjais/LoadBotTesting-2) repo.

When ARI is run over the play, `debug` module isn't being updated to `ansible.builtin.debug`.

**Comment by hirokuni-kitahara** [comment] 2024-06-19 09:25
Let me close this issue because this is duplicate of https://github.com/ansible/ansible-risk-insight/issues/232 and 232 is more detail. Thank you.

**Closed by hirokuni-kitahara** 2024-06-19 09:25 UTC
